apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-demo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-demo
  template:
    metadata:
      labels:
        app: node-demo
    spec:
      containers:
      - name: node-demo
        image: abhiram668/node-docker-k8s-demo:latest
        ports:
        - containerPort: 3000
